trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: "azure-sc"

steps:          
  - task: AzureCLI@2
    displayName: Biceps deployment via CLI
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptLocation: "inlineScript"
      inlineScript: |
       $out = az deployment group create -f $(Build.SourcesDirectory)/deploy/main.bicep -g alexandria -p $(Build.SourcesDirectory)/deploy/parameters.ci.json

       $provisionOutputs = [PSCustomObject]@{}
        $out | Get-Member -MemberType NoteProperty | ForEach-Object {

            $name = $_.name
            $provisionOutputs | Add-Member -MemberType NoteProperty -Name $name -value $out.$name.value
            Write-Host "##vso[task.setvariable variable=$($name);isOutput=true]$($out.$name.value)"
        }
        $provisionOutputs
      scriptType: "pscore"

  # - task: PowerShell@2
  #   name: 'SetDeploymentOutputVariables'
  #   displayName: 'Set Deployment Output Variables'
  #   inputs:
  #     targetType: inline
  #     script: |
  #       $armOutputObj = '$(deploymentOutputs)' | ConvertFrom-Json
  #       $armOutputObj.PSObject.Properties | ForEach-Object {
  #         $keyname = $_.Name
  #         $value = $_.Value.value

  #         # Creates a standard pipeline variable
  #         Write-Output "##vso[task.setvariable variable=$keyName;issecret=true]$value"

  #         # Display keys in pipeline
  #         Write-Output "output variable: $keyName"
  #       }
  #     pwsh: true

  - task: AzureStaticWebApp@0
    inputs:
      app_location: /
      api_build_command: yarn run build
      output_location: /dist/alexandria
      azure_static_web_apps_api_token: $(deployment_token)
      
