trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: "azure-sc"

steps:          
  - task: AzureCLI@2
    displayName: Biceps deployment via CLI
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptLocation: "inlineScript"
      inlineScript: |
       $out = az deployment group create -f $(Build.SourcesDirectory)/deploy/main.bicep -g alexandria -p $(Build.SourcesDirectory)/deploy/parameters.ci.json

       deployment_token=$(az deployment sub show  -n '$(Build.BuildId)' --query properties.outputs.deployment_token.value | tr -d '"')
                  echo "instrumentation key is $deployment_token"
                  echo "##vso[task.setvariable variable=deployment_token;isOutput=true]$deployment_token"
      scriptType: "pscore"

  - task: AzureStaticWebApp@0
    inputs:
      app_location: /
      api_build_command: yarn run build
      output_location: /dist/alexandria
      api_location: /api
      azure_static_web_apps_api_token: $(deployment_token)
      
