trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'azure-sc'
  testprojects: 'api/tests/**/*.UnitTests.csproj'

stages:
  - template: build-pipeline.yaml
    parameters:
      name: ci-staging
      dependsOn: []

  - template: build-pipeline.yaml
    parameters:
      name: ci
      dependsOn: [ci-staging]
