trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: "azure-sc"

steps:          
  - task: AzureCLI@2
    displayName: Biceps deployment via CLI
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      inlineScript: "az deployment group create -f $(Build.SourcesDirectory)/deploy/main.bicep -g alexandria -p $(Build.SourcesDirectory)/deploy/parameters.ci.json"
